apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tars

resources:
  - service.yaml
  - deployment.yaml

images:
  - name: ghcr.io/agustinsacco/tars/tars-docs
    newName: ghcr.io/agustinsacco/tars/tars-docs
