apiVersion: v1
kind: Service
metadata:
  name: tars-docs
  namespace: tars
  labels:
    app: tars-docs
spec:
  selector:
    app: tars-docs
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4242
      targetPort: 4242
      name: http
